def gf_gen(T=0) -> list:
    import random
    staaten = ['afghanisch', 'albanisch', 'algerisch', 'amerikanisch', 'Andorran', 'Angolaner', 'Antiguaner', 'argentinisch', 'Armenisch', 'australisch', 'österreichisch', 'Aserbaidschani', 'Bahamian', 'Bahraini', 'Bangladeschi', 'Barbadier', 'Barbudans', 'Batswana', 'Weißrussland', 'Belgier', 'Belizean', 'Beninesen', 'Bhutaner', 'bolivianisch', 'bosnisch', 'Brasilianer', 'britisch', 'Bruneian', 'bulgarisch', 'Burkinabe', 'birmanisch', 'Burundisch', 'Kambodschaner', 'Kameruner', 'kanadisch', 'Kap Verdean', 'Zentralafrikaner', 'Chadier', 'chilenisch', 'chinesisch', 'kolumbianisch', 'Komor', 'Kongolesisch', 'Costa Ricaner', 'kroatisch', 'Kubaner', 'Zypriot', 'tschechisch', 'dänisch', 'Dschibuti', 'dominikanisch', 'Niederländisch', 'Osttimorisch', 'Ecuadorean', 'ägyptisch', 'Emirian', 'Äquatoriale Guineaner', 'Eritreik', 'estnisch', 'äthiopisch', 'Fidschian', 'Filipino', 'finnisch', 'Französisch', 'Gabonesisch', 'Gambian', 'georgisch', 'Deutsch', 'ghanaisch', 'griechisch', 'Grenadian', 'guatemaltekisch', 'Guinea-Bissauan', 'Guinesisch', 'Guyanese', 'haitianisch', 'Herzegoviner', 'honduranisch', 'ungarisch', 'I-kiribati', 'Isländer', 'indisch', 'Indonesisch', 'iranisch', 'irakisch', 'irisch', 'israelisch', 'Italienisch', 'Ivorer', 'jamaikanisch', 'japanisch', 'Jordanier', 'Kasachstani', 'Kenianer', 'Kittian und Nesian', 'Kuwaiti', 'Kirgisische', 'Laotisch', 'lettisch', 'libanesisch', 'Liberian', 'Libyer', 'Liechtensteiner', 'litauisch', 'Luxemburger', 'mazedonisch', 'Madagasy', 'Malawisch', 'malaysisch', 'Maldivan', 'Malian', 'maltesisch', 'Marshalle', 'Mauriter', 'Mauritianer', 'Mexikaner', 'Mikronesisch', 'Moldawien', 'Monacan', 'mongolisch', 'marokkanisch', 'Mosotho', 'Motswana', 'Mosambikan', 'Namibian', 'Nauruan', 'Nepalese', 'Neuseeländer', 'Nicaraguan', 'Nigerianer', 'Nigerien', 'nordkoreanisch', 'Nordirisch', 'norwegisch', 'Omani', 'pakistanisch', 'Palauan', 'Panamaer', 'Papua -Neuguineaner', 'Paraguayan', 'peruanisch', 'Polieren', 'Portugiesisch', 'Katari','kurde', 'rumänisch', 'Russisch', 'Ruandan', 'Heiliger Lucian', 'Salvadoran', 'Samoaner', 'San Marinese', 'Sao tonean', 'Saudisch', 'schottisch', 'senegalesisch', 'serbisch', 'Seychellois', 'Sierra Leonean', 'Singapurer', 'Slowakisch', 'Slowenisch', 'Solomon Islander', 'somali', 'Südafrikanisch', 'südkoreanisch', 'Spanisch', 'Sri Lankan', 'Sudanese', 'Surinamer', 'Swazi', 'Schwedisch', 'Schweizer', 'syrisch', 'Taiwanese', 'Tajik', 'Tansanian', 'Thai', 'Togolesisch', 'Tongan', 'Trinidadianer oder Tobonier', 'Tunesisch', 'Türkisch', 'Tuvaluan', 'Ugandan', 'ukrainisch', 'Uruguayan', 'Usbekistani', 'venezolanisch', 'Vietnamesisch', 'Walisisch', 'Jemenit', 'Sambianer', 'simbabwisch']
    if T==1:
        return staaten

    mutter_nr = random.randint(0, len(staaten) - 1)
    mutter_nat = staaten[mutter_nr]

    vater_nr = random.randint(0, len(staaten) - 1)
    vater_nat = staaten[vater_nr]
    
    return mutter_nat, vater_nat